### ISSUE TITLE
Undefined simbol

### ISSUE THREAD

**Issue by astrorafael** [taxelrod/indigo_cffi#1]
Hi

I'm trying to use your project for some python INDIGO automation. Your project comes handy for this, thank you!

I',m using Ubuntu 18.0.4 LTS
 I downloaded the latest indigo (master branch), compiled it fine, download yours, compiled it fine as well (althoug I had to change include_dirs to `include_dirs = ['../indigo_libs/indigo']`) , set the PYTHONPATH but received an error, an undefined symbol in the generated shared library. Are you able to reproduce this?

```bash
 {master} ~/repos/indigo/indigo_cffi$ export PYTHONPATH=`pwd`
 {master} ~/repos/indigo/indigo_cffi$ python3 Examples/dumpProperties.py 
Traceback (most recent call last):
  File "Examples/dumpProperties.py", line 25, in <module>
    import indigo
  File "/home/rafa/repos/indigo/indigo_cffi/indigo.py", line 37, in <module>
    from _indigo import ffi, lib
ImportError: /home/rafa/repos/indigo/indigo_cffi/_indigo.cpython-36m-x86_64-linux-gnu.so: undefined symbol: indigo_get_master_token
```

**Comment by polakovic** [comment]
You need to add indigo_libs/indigo_token.c.

**Comment by astrorafael** [comment]
Thanks. Now it works. However, there is now a runtime error due to structure aligment offsets. It may happen that the cdefs have changed between the real code and your module.

**EDIT**. Verified. I replaced all the structure definitions from the sources and now it works.

**Comment by polakovic** [comment]
yes, structure definition changed with token support. you have to rebuild everything.
